table _Measures
	lineageTag: d6228b0f-5278-434c-9881-7d03e3958f78

	measure 'Total Sales Amount' = SUM(transactions[norm_sales_amount])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Sales
		lineageTag: 91dd52e9-f77c-498e-ae7a-e43937129174

	measure 'Total Sales Quantity' = SUM(transactions[sales_qty])
		formatString: 0
		displayFolder: Sales
		lineageTag: 97ff678b-4ee0-4586-8f3c-0fc2e16a6615

	measure 'Avg Sales Price' = DIVIDE([Total Sales Amount],[Total Sales Quantity])
		displayFolder: Sales
		lineageTag: b5ba8dd2-d4d9-44e0-9a90-c41ac6389445

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YOY Growth Sales' = CALCULATE([Total Sales Amount], SAMEPERIODLASTYEAR(transactions[norm_sales_amount]))
		formatString: 0
		displayFolder: Sales
		lineageTag: 86fb891a-d510-4b01-8f4f-9883a354d5a8

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

