table _Measures
	lineageTag: d6228b0f-5278-434c-9881-7d03e3958f78

	measure Revenue = SUM(transactions[norm_sales_amount])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 91dd52e9-f77c-498e-ae7a-e43937129174

	measure 'Sales Qty' = SUM(transactions[sales_qty])
		formatString: 0
		lineageTag: 97ff678b-4ee0-4586-8f3c-0fc2e16a6615

	measure 'Total Profit Margin' = SUM(transactions[profit_margin])
		lineageTag: f40dca83-3fbb-4488-900d-d0e5d86fbf57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Margin %' = DIVIDE([Total Profit Margin],[Revenue],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fc06660b-3159-4e1a-ba86-40ac250562a8

	measure 'Profit Margin contribution %' = DIVIDE([Total Profit Margin],CALCULATE([Total Profit Margin], ALL(products), ALL(customers),ALL(markets)))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6d7df818-ef3e-4707-8fc4-cd62f7a97e1f

	measure 'Revenue contribution %' = DIVIDE([Revenue],CALCULATE([Revenue],  ALL(products), ALL(customers), ALL(markets)))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f8c8ad25-bccd-4fb0-9a8d-1d1a948c1239

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

