table _Measures
	lineageTag: d6228b0f-5278-434c-9881-7d03e3958f78

	measure 'Total Sales Amount' = SUM(transactions[norm_sales_amount])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Sales
		lineageTag: 91dd52e9-f77c-498e-ae7a-e43937129174

	measure 'Total Sales Quantity' = SUM(transactions[sales_qty])
		formatString: #,0
		displayFolder: Sales
		lineageTag: 97ff678b-4ee0-4586-8f3c-0fc2e16a6615

	measure 'Avg Sales Price' = DIVIDE([Total Sales Amount],[Total Sales Quantity])
		displayFolder: Sales
		lineageTag: b5ba8dd2-d4d9-44e0-9a90-c41ac6389445

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YOY Sales Growth' = DIVIDE([Total Sales Amount] - [Total Sales SPLY], [Total Sales SPLY], 0)
		displayFolder: YOY Sales
		lineageTag: 86fb891a-d510-4b01-8f4f-9883a354d5a8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales SPLY' = CALCULATE([Total Sales Amount], SAMEPERIODLASTYEAR(Dates[Date]))
		displayFolder: YOY Sales
		lineageTag: 45c914e5-f617-4082-8d58-4a4c5c64dced

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales PM' = CALCULATE([Total Sales Amount], PARALLELPERIOD(Dates[Date],-1,MONTH))
		displayFolder: MOM Sales
		lineageTag: 4f48e471-68e6-4435-bd9b-f4b525cb621c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MOM Sales Growth' = DIVIDE([Total Sales Amount]-[Total Sales PM], [Total Sales PM],0)
		displayFolder: MOM Sales
		lineageTag: ba541675-c158-4727-82c6-e659d3185f33

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Margin %' = ```
			DIVIDE([Profit],[Total Sales Amount],0 ) 
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales
		lineageTag: 59dfbf26-3859-442c-81a7-9621717c0f63

	measure 'Total Sales per Customer' = CALCULATE(SUM(transactions[norm_sales_amount]), ALLEXCEPT(customers,customers[customer_code]))
		displayFolder: Sales
		lineageTag: d03b653e-e634-4ae8-8551-f62d3bb63f5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer Sales Rank' = RANKX(ALL(customers[customer_code]),[Total Sales per Customer],,DESC,Dense)
		formatString: 0
		displayFolder: Sales
		lineageTag: 59e11dea-12c4-4fa8-8cbe-47fc2bea7feb

	measure 'Is Top 5 Customer' = IF([Customer Sales Rank] <= 5, TRUE(), FALSE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Sales
		lineageTag: 08fdd3fa-40b1-4a3a-875a-d74aef01d857

	measure 'Average Sales Per Order' = ```
			DIVIDE([Total Sales Amount],[Total Order], 0) 
			
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Sales
		lineageTag: 6005b15b-7b7f-4b2d-8d83-597ce63c6c1b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Greetings = ```
			
			VAR CurrentTime = NOW()
			VAR Namee = "Adordev"
			VAR Greeting = 
			    SWITCH(
			        TRUE(),
			        HOUR(CurrentTime) < 12, "Good Morning",
			        HOUR(CurrentTime) < 18, "Good Afternoon",
			        "Good Evening"
			    )
			RETURN 
			   Greeting & " - " & Namee
			```
		displayFolder: Sales
		lineageTag: 33785685-0dbc-4b1b-94d6-af9fbe1124d3

	measure 'Total Order' = count(transactions[transaction_id])
		formatString: #,0
		displayFolder: Order
		lineageTag: 78437915-9799-4106-b941-43954bc24472

	measure 'Total Cost' = ```
			SUM(transactions[norm_cost])
			
			```
		displayFolder: Sales
		lineageTag: 45fbe6de-d25a-48c2-a9cf-8295bc4dc3f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Profit = [Total Sales Amount] - [Total Cost]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Sales
		lineageTag: cdeb49c4-5aa8-4087-bc2a-7e690f2b9414

	measure 'YOY Sales Growth Trend Icon' = ```
			
			VAR PositiveIcon = UNICHAR(9650)
			VAR NegativeIcon = UNICHAR(9660)
			VAR Choice = IF([YOY Sales Growth] > 0, PositiveIcon , NegativeIcon)
			VAR Display = Choice & " " & FORMAT([YOY Sales Growth], "0.00%")
			Return Display
			
			```
		displayFolder: YOY Sales
		lineageTag: 1d492fcc-6580-4d08-bd25-b2a979432d67

	measure 'MOM Sales Growth Trend Icon' = ```
			
			VAR PositiveIcon = UNICHAR(9650)
			VAR NegativeIcon = UNICHAR(9660)
			VAR Choice = IF([MOM Sales Growth] > 0, PositiveIcon , NegativeIcon)
			VAR Display = Choice & " " & FORMAT([MOM Sales Growth], "0.00%")
			Return Display
			
			```
		displayFolder: MOM Sales
		lineageTag: f5408a6f-6189-4863-86ab-d6c8dbb59b01

	measure 'YOY Trend Color' = IF([YOY Sales Growth] < 0, "Red", "Green")
		displayFolder: YOY Sales
		lineageTag: c5a8b412-ec37-4030-97bc-9b6834d1faf3

	measure 'MOM Trend Color' = IF([MOM Sales Growth] < 0, "Red", "Green")
		displayFolder: MOM Sales
		lineageTag: 729ffba1-f696-4f38-a854-67a923ae2843

	measure 'Total Quantity SPLY' = CALCULATE([Total Sales Quantity], SAMEPERIODLASTYEAR(Dates[Date]))
		formatString: 0
		displayFolder: YOY Quantity
		lineageTag: bfa25a03-6653-4b58-a38b-7d1c413547f2

	measure 'YOY QTY Growth' = DIVIDE([Total Sales Quantity]-[Total Quantity SPLY],[Total Sales SPLY], 0)
		displayFolder: YOY Quantity
		lineageTag: 690e7fc4-2123-416a-b3a9-7d8947abecf3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YOY Qty Growth Trend Icon' = ```
			
			VAR PositiveIcon = UNICHAR(9650)
			VAR NegativeIcon = UNICHAR(9660)
			VAR Choice = IF([YOY QTY Growth] > 0, PositiveIcon , NegativeIcon)
			VAR Display = Choice & " " & FORMAT([YOY QTY Growth], "0.00%")
			Return Display
			
			```
		displayFolder: YOY Quantity
		lineageTag: 1ce9a1b6-16bc-4c68-aad6-c955724f78f3

	measure 'YOY Qty Trend Color' = IF([YOY QTY Growth] < 0, "Red", "Green")
		displayFolder: YOY Quantity
		lineageTag: 99d22583-0fb1-42fd-becf-ebb15964926e

	measure 'Total Qty PM' = CALCULATE([Total Sales Quantity], PARALLELPERIOD(Dates[Date],-1,MONTH))
		formatString: 0
		displayFolder: MOM Quantity
		lineageTag: 4727cd1c-f679-4c8f-be34-74ed526f2d1b

	measure 'MOM Quantity Growth' = DIVIDE([Total Sales Quantity]-[Total Qty PM],[Total Qty PM],0)
		displayFolder: MOM Quantity
		lineageTag: efe4e805-07c5-43db-b189-444bfd47acd9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MOM Qty Growth Trend Icon' = ```
			
			VAR PositiveIcon = UNICHAR(9650)
			VAR NegativeIcon = UNICHAR(9660)
			VAR Choice = IF([MOM Quantity Growth] > 0, PositiveIcon , NegativeIcon)
			VAR Display = Choice & " " & FORMAT([MOM Quantity Growth], "0.00%")
			Return Display
			
			```
		displayFolder: MOM Quantity
		lineageTag: 0242ecba-1a52-4b79-abde-36d82c45a2e0

	measure 'MOM QTY Trend Color' = IF([MOM Quantity Growth] < 0, "Red", "Green")
		displayFolder: MOM Quantity
		lineageTag: bbc1c8bd-f2b6-4ee6-aa4b-caadd0a67ce2

	measure 'Total N of Customers' = COUNT(customers[customer_code])
		formatString: 0
		displayFolder: Customer
		lineageTag: a494165c-b83a-479b-9781-af88107e32cd

	measure 'Avg Sales per Customer' = DIVIDE([Total Sales Amount],[Total N of Customers],0)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Customer
		lineageTag: ac44d4ed-2d36-43b0-b488-0794f433663a

	measure 'First Purchase Date' = ```
			
			CALCULATE(
			    MIN(Dates[Date]),
			    ALLEXCEPT(transactions, transactions[customer_code])
			)
			
			```
		formatString: General Date
		displayFolder: Sales
		lineageTag: 6c97e2d3-7c56-40db-9354-2f8b9dda7dad

	measure 'Customer Type' = ```
			
			IF(
			    MIN(Dates[Date]) = [First Purchase Date],
			    "New",
			    "Repeat"
			)
			
			
			```
		displayFolder: Sales
		lineageTag: 19118471-a5e5-4a93-96bd-add1e9217d20

	measure 'Last Transaction Date' = ```
			
			CALCULATE(
			    MAX(Dates[Date]),
			    ALLEXCEPT(transactions, transactions[customer_code])
			)
			
			```
		formatString: General Date
		displayFolder: Sales
		lineageTag: b53f2862-0e08-41b4-a981-493ffda95b8c

	measure 'Inactive Period (Days)' = ```
			
			DATEDIFF(
			    [Last Transaction Date],
			    TODAY(),
			    DAY
			)
			
			```
		formatString: 0
		displayFolder: Sales
		lineageTag: 4d46f6bc-91b1-49bd-a92b-7862fe8d8686

	measure 'Churned Customer' = ```
			
			IF(
			    [Inactive Period (Days)] > 90,
			    "Churned",
			    "Active"
			)
			
			```
		displayFolder: Sales
		lineageTag: d4c49f8f-b446-423b-9a27-bb96989b4186

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

