table _Measures
	lineageTag: d6228b0f-5278-434c-9881-7d03e3958f78

	measure 'Total Sales Amount' = SUM(transactions[norm_sales_amount])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Sales
		lineageTag: 91dd52e9-f77c-498e-ae7a-e43937129174

	measure 'Total Sales Quantity' = SUM(transactions[sales_qty])
		formatString: #,0
		displayFolder: Sales
		lineageTag: 97ff678b-4ee0-4586-8f3c-0fc2e16a6615

	measure 'Avg Sales Price' = DIVIDE([Total Sales Amount],[Total Sales Quantity])
		displayFolder: Sales
		lineageTag: b5ba8dd2-d4d9-44e0-9a90-c41ac6389445

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YOY Sales Growth' = DIVIDE([Total Sales Amount] - [Total Sales SPLY], [Total Sales SPLY], 0)
		formatString: 0.00
		displayFolder: YOY Sales
		lineageTag: 86fb891a-d510-4b01-8f4f-9883a354d5a8

	measure 'Total Sales SPLY' = CALCULATE([Total Sales Amount], SAMEPERIODLASTYEAR(Dates[Date]))
		displayFolder: YOY Sales
		lineageTag: 45c914e5-f617-4082-8d58-4a4c5c64dced

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YOY Sales checkamte' = ```
			
			(CALCULATE(SUM(transactions[norm_sales_amount]), SAMEPERIODLASTYEAR(Dates[Date])) - SUM(transactions[norm_sales_amount])) 
			/ CALCULATE(SUM(transactions[norm_sales_amount]), SAMEPERIODLASTYEAR(Dates[Date]))
			
			```
		displayFolder: YOY Sales
		lineageTag: e984a201-9661-4fd7-b1dc-18eb9bb1aa53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Sales PM' = CALCULATE([Total Sales Amount], PARALLELPERIOD(Dates[Date],-1,MONTH))
		displayFolder: MOM Sales
		lineageTag: 4f48e471-68e6-4435-bd9b-f4b525cb621c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MOM Sales Growth' = DIVIDE([Total Sales Amount]-[Total Sales PM], [Total Sales PM],0)
		displayFolder: MOM Sales
		lineageTag: ba541675-c158-4727-82c6-e659d3185f33

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Margin %' = (SUM(transactions[profit_margin]) / SUM(transactions[norm_sales_amount]))  * 100
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales
		lineageTag: 59dfbf26-3859-442c-81a7-9621717c0f63

	measure 'Total Sales per Customer' = CALCULATE(SUM(transactions[norm_sales_amount]), ALLEXCEPT(customers,customers[customer_code]))
		displayFolder: Sales
		lineageTag: d03b653e-e634-4ae8-8551-f62d3bb63f5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer Sales Rank' = RANKX(ALL(customers[customer_code]),[Total Sales per Customer],,DESC,Dense)
		formatString: 0
		displayFolder: Sales
		lineageTag: 59e11dea-12c4-4fa8-8cbe-47fc2bea7feb

	measure 'Is Top 5 Customer' = IF([Customer Sales Rank] <= 5, TRUE(), FALSE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Sales
		lineageTag: 08fdd3fa-40b1-4a3a-875a-d74aef01d857

	measure 'Total Profit Margin' = ```
			sum(transactions[profit_margin])
			
			```
		displayFolder: Sales
		lineageTag: 6005b15b-7b7f-4b2d-8d83-597ce63c6c1b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Greetings = ```
			
			VAR CurrentTime = NOW()
			VAR Namee = "Adordev"
			VAR Greeting = 
			    SWITCH(
			        TRUE(),
			        HOUR(CurrentTime) < 12, "Good Morning",
			        HOUR(CurrentTime) < 18, "Good Afternoon",
			        "Good Evening"
			    )
			RETURN 
			   Greeting & " - " & Namee
			```
		displayFolder: Sales
		lineageTag: 33785685-0dbc-4b1b-94d6-af9fbe1124d3

	measure 'Total Order' = count(transactions[order_date])
		formatString: 0
		displayFolder: Order
		lineageTag: 78437915-9799-4106-b941-43954bc24472

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

